### PR TITLE
Project file fixes after applying recommended settings in 9.1

### PR DESCRIPTION
**Pull request by jhudsonWA**

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Regarding the request here: https://github.com/CocoaPods/CocoaPods/issues/7206

**Comment by segiddins** [comment]
I think you wanted something like this:

```diff
diff --git a/lib/xcodeproj/constants.rb b/lib/xcodeproj/constants.rb
index df20434..3016f49 100644
--- a/lib/xcodeproj/constants.rb
+++ b/lib/xcodeproj/constants.rb
@@ -4,17 +4,17 @@ module Xcodeproj
   module Constants
     # @return [String] The last known iOS SDK (stable).
     #
-    LAST_KNOWN_IOS_SDK = '10.3'
+    LAST_KNOWN_IOS_SDK = '11.1'
 
     # @return [String] The last known OS X SDK (stable).
     #
-    LAST_KNOWN_OSX_SDK = '10.12'
+    LAST_KNOWN_OSX_SDK = '10.13'
 
     # @return [String] The last known tvOS SDK (stable).
-    LAST_KNOWN_TVOS_SDK = '10.2'
+    LAST_KNOWN_TVOS_SDK = '11.0'
 
     # @return [String] The last known watchOS SDK (stable).
-    LAST_KNOWN_WATCHOS_SDK = '3.2'
+    LAST_KNOWN_WATCHOS_SDK = '4.1'
 
     # @return [String] The last known archive version to Xcodeproj.
     #
@@ -22,7 +22,7 @@ module Xcodeproj
 
     # @return [String] The last known Swift version (stable).
     #
-    LAST_KNOWN_SWIFT_VERSION = '3.0'
+    LAST_KNOWN_SWIFT_VERSION = '4.0'
 
     # @return [String] The default object version for Xcodeproj.
     DEFAULT_OBJECT_VERSION = 46
@@ -37,7 +37,7 @@ module Xcodeproj
 
     # @return [String] The last known object version to Xcodeproj.
     #
-    LAST_SWIFT_UPGRADE_CHECK = '0830'
+    LAST_SWIFT_UPGRADE_CHECK = '0910'
 
     # @return [String] The version of `.xcscheme` files supported by Xcodeproj
     #
```

**Comment by jhudsonWA** [comment]
I was asked to do a pull request on here not just a diff. 🤷🏼‍♂️

**Comment by dnkoutso** [comment]
@segiddins I thought that `ruby spec/fixtures/CommonBuildSettings/rebuild_from_xcode` was the command to run to update xcodeproj settings. I am still unclear on what is the correct process to update xcodeproj settings.

**Comment by jhudsonWA** [comment]
All that did was create a new Xcode project file I thought..

**Comment by segiddins** [comment]
@dnkoutso it is, and I ran it locally with 9.1 and there were no changes

**Comment by jhudsonWA** [comment]
Then it must not be fully working. If you click link above to original issue you can see the 9.1 screenshot of what upgrades it wants.

**Comment by dnkoutso** [comment]
Yes i've tried using the script for Xcode 9 and saw zero changes. I am uncertain how to proceed.

**Comment by freak4pc** [comment]
The problem seems to be the absence of Whole-Module optimization.

f5af548c-c2d9-4cd2-9e4c-c66d429524b3

**Comment by dnkoutso** [comment]
superseded by https://github.com/CocoaPods/Xcodeproj/pull/541

**Pull request closed without merging**
