### PR TITLE
Fix incorrect formatting of build settings with modifiers

### LINKED ISSUE #666: Incorrectly changing the formatting of the GCC_PREPROCESSOR_DEFINITIONS config
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod install`.

## What did you expect to happen?

The project file should not be modified.

## What happened instead?

The project file modified from:

```
"GCC_PREPROCESSOR_DEFINITIONS[sdk=iphonesimulator*]" = (
	"$(inherited)",
	"SIMULATOR=1",
);
```

to

```
"GCC_PREPROCESSOR_DEFINITIONS[sdk=iphonesimulator*]" = "$(inherited) SIMULATOR=1";
```

There are 2 issues with this behavior:

1. It is not consistent with other configs, e.g:

```
FRAMEWORK_SEARCH_PATHS = (
	"$(PROJECT_DIR)",
	"$(PROJECT_DIR)/Frameworks",
);
```

was not changed.

2. Triggering an update for the project file in Xcode (e.g. by changing and reverting any config) reverts it to the old format.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 16880e8b4d2d4fbed5b92f89e7ceaa81e0940a52
               // redacted
```

### Installation Source

```
Executable Path: /Users/iulian/.gems/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# frozen_string_literal: true

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

install!('cocoapods', share_schemes_for_development_pods: false)

# redacted

post_install do |installer|
    puts("\nUpdating TwitterKit Pod's resources")

    pods_directory_name = 'Pods'
    twitter_kit_pod_name = 'TwitterKit'
    twitter_kit_resources_bundle_file_name = 'TwitterKitResources.bundle'
    twitter_heart_animation_name = 'twtr-heart-animation-sheet'
    transparent_pixel_image_encoded_data = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='
    transparent_pixel_image_decoded_data = Base64.decode64(transparent_pixel_image_encoded_data)

    pods_project = installer.pods_project
    pods_project_group = pods_project.groups.find { |group| group.name == pods_directory_name }
    twitter_kit_project_group = pods_project_group.groups.find { |group| group.name == twitter_kit_pod_name }
    twitter_kit_resources_project_group = twitter_kit_project_group.groups.find { |group| group.name == 'Resources' }
    twitter_kit_resources_bundle_file = twitter_kit_resources_project_group.files.find { |file| file.name == twitter_kit_resources_bundle_file_name }
    twitter_kit_resources_bundle_file_path = twitter_kit_resources_bundle_file.path
    twitter_kit_resources_bundle_file_full_path = "#{pods_directory_name}/#{twitter_kit_pod_name}/#{twitter_kit_resources_bundle_file_path}/"

    Dir.glob(twitter_kit_resources_bundle_file_full_path + twitter_heart_animation_name + '*').each do |file_path|
        File.open(file_path, 'wb') do |file|
            file.write(transparent_pixel_image_decoded_data)
        end
    end

    puts("\nUpdating Pods project's targets")

    pod_build_settings_names = %w[HEADER_SEARCH_PATHS LIBRARY_SEARCH_PATHS OTHER_CFLAGS OTHER_LDFLAGS]

    installer.pods_project.targets.each do |pod_target|
        puts("\tUpdating \"#{pod_target.name}\" target")

        pod_target.build_configurations.each do |build_configuration|
            if pod_target.name == 'FLEX'
                build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'SQLITE_HAS_CODEC=1']
                build_configuration.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/Headers/Public/SQLCipher']
            end

            xcconfig_path = build_configuration.base_configuration_reference.real_path

            xcconfig = File.read(xcconfig_path)

            xcconfig.slice!(' -l"sqlite3"')

            unless (pod_target.name =~ /^Pods-/).nil?
                pod_build_settings_names.each do |build_setting_name|
                    xcconfig.sub!(/^(#{build_setting_name})/, 'PODS_\1')
                end
            end

            File.open(xcconfig_path, 'w') { |file| file << xcconfig }
        end
    end

    puts("\nUpdating project's targets")

    warnings = {
        'deprecated-declarations': ['ZipArchive'],
        'undeclared-selector': ['ZipArchive'],
        'unused-function': ['zip'],
        'unused-variable': ['unzip']
    }

    project = installer.aggregate_targets.first.user_project

    targets = project.native_targets.reject do |target|
        target.name.include?('Watch') || target.name.include?('Test')
    end

    targets.each do |target|
        puts("\tUpdating \"#{target.name}\" target")

        source_files = target.source_build_phase.files

        source_files.each do |source_file|
            source_file_name = File.basename(source_file.display_name, '.*')
            compiler_flags = []

            source_file.settings = nil

            warnings.each do |flag_name, files|
                compiler_flags << "-Wno-#{flag_name}" if files.include?(source_file_name)
            end

            source_file.settings = { 'COMPILER_FLAGS': compiler_flags.join(' ') } unless compiler_flags.empty?
        end
    end

    puts("\n\tSaving project")

    project.save()

    puts()
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

### PR DESCRIPTION
**Pull request by revolter**
Fixes #666 😈

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix incorrect formatting of build settings with modifiers  
  [revolter](https://github.com/revolter)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by revolter** [comment]
Should I add a test case for this?

**Comment by dnkoutso** [comment]
Yes please!

**Comment by revolter** [comment]
Done!

**Comment by revolter** [comment]
What's the issue?

**Comment by dnkoutso** [comment]
Something is wrong with build on "xit or fit left in tests (spec/project/object/build_configuration_spec.rb)"

LGTM otherwise.

**Comment by revolter** [comment]
I fixed it, but it's weird that it was already in master but the last commits on master are green.

**Comment by dnkoutso** [comment]
Hm maybe danger was updated. If the test was disabled we can even delete it as it probably has been disable for a while.

**Comment by revolter** [comment]
I think that it was only a mistake, and we actually do need those tests. They were added in https://github.com/CocoaPods/Xcodeproj/commit/7b5c7807a0c71d7f3d85f6b7dec60283095a38f0.

**Comment by revolter** [comment]
Yeah, it looks like the tests are indeed wrong.

**Comment by revolter** [comment]
I think that the bug that the tests are trying to prevent still exists and will need to be fixed in the future, but that doesn't have anything to do with my changes, so if all is good, this should be merged.

**Comment by revolter** [comment]
@dnkoutso, Could you please merge this? 😃

**Comment by dnkoutso** [comment]
/?hmmm I'd like to fix the build first. Maybe in a separate PR

**Comment by revolter** [comment]
Will you or @segiddins take care of it? And, when will be the next release? I'm worried that it will take a lot of time until I get this change, as it has to be released in a new Xcodeproj version, then create a PR in CocoaPods, then get it merged, then wait for a new CocoaPods release 😟

**Comment by dnkoutso** [comment]
You can use Bundler https://bundler.io/v1.12/git.html to pin to your fork or branch if this change is blocking you and you don't want to wait for a release, which is understandable.

**Comment by revolter** [comment]
Wouldn't be better if this was merged now? As you're obviously very busy and you won't ever fix those old failing checks unrelated to this change.

**Comment by barakwei** [comment]
Can this be merged? Looks like tests are passing, and there's some unrelated issue.

**Comment by segiddins** [comment]
```
Danger has failed this build. 
Found 1 error.
```

**Comment by barakwei** [comment]
Can we please move the forward somehow? it seems like a CI failure to me and not something in the PR. Can we run CI again?

**Comment by segiddins** [comment]
Re-kicked CI

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><code>xit</code> or <code>fit</code> left in tests (spec/project/object/build_configuration_spec.rb)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by revolter** [comment]
Ok, so in other PRs, there's

**Comment by revolter** [comment]
So knowing that it will take a looot of time until this gets into CocoaPods, please merge it as soon as possible, and try to make a new release containing this, again, as soon as possible.

**Comment by revolter** [comment]
Also, is it ok that `DANGER_GITHUB_API_TOKEN` can be found in https://api.travis-ci.org/v3/job/607538923/log.txt?

**Comment by segiddins** [comment]
cc @orta on the danger issue

**Comment by segiddins** [comment]
@revolter 

> Sorry, but, this is bullshit

I'm sorry, but this attitude is not acceptable. CocoaPods is maintained by people in their spare time, and complaining rudely about failing builds or slow release cycles will not make anything happen faster.

**Comment by revolter** [comment]
@segiddins, You're right, I'm sorry for using that word, but I consider that I did everything I could, and the only thing I needed for you was to merge it, nothing more, no extra work.

> complaining rudely about failing builds or slow release cycles will not make anything happen faster.

I did not do this. I complained about ignoring my "research" related to the issue, that concluded in the fact that it was 100% not introduced by me in this PR.
And I surely didn't complain about slow release cycles, I completely understand it, it was provided as an extra reason of merging my work. I waited 3 months, so I can wait more.
Also, not only did I not complain, I also spent time to look into it, [git blame it](https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-521387643), [try to fix them myself, even if completely unrelated](https://github.com/CocoaPods/Xcodeproj/commit/bbd537a440d4abf4fc31275c65f7d6046cd7e592), and I was met with rejections without a reason ([1](https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-522447383), [2](https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-530189770)) or [simply ignored](https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-527838029).

So, again, I know a little about maintaining open source projects, I completely understand the huge effort and time spent by the maintainers, and I have no problem whatsoever to do everything I can to make your job easier.

**Comment by revolter** [comment]
Also, it's weird that there is a Danger check with is green, but the CI check fails because of Danger.

**Comment by orta** [comment]
The message is here: https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-541374052

Screen Shot 2019-11-07 at 8 48 11 AM

**Comment by revolter** [comment]
@orta, Yes, `xit` is the cause. The problem is that other (some) PRs don't trigger this, and this is logged:

> Danger does not have write access to the PR to set a PR status.

**Comment by orta** [comment]
The dangerfile only looks [at modified files](https://github.com/CocoaPods/cocoapods/blob/master/Dangerfile#L3) for the `xit`/`fit` checks, and this PR includes those changes - and don't worry about the status update message, that's because the CI version doesn't have write access to the repo, which we want.

**Comment by revolter** [comment]
Got it, thanks a lot!

**Comment by revolter** [comment]
@orta, What about https://github.com/CocoaPods/Xcodeproj/pull/706#issuecomment-549741086?

**Comment by orta** [comment]
Yep, totally fine, this is set up right - https://danger.systems/guides/faq.html#why-am-i-seeing-quot-set-status-failed-quot-on-my-github-oss-project

**Comment by revolter** [comment]
As #727 was merged, I rebased this branch and it builds successfully, so this is now ready for merge.

**Comment by revolter** [comment]
To use this fix before it gets officially released, add an explicit `xcodeproj` gem dependency in your `Gemfile` like:

```ruby
# frozen_string_literal: true

source 'https://rubygems.org' do
    gem 'cocoapods'
    gem 'xcodeproj', git: 'https://github.com/CocoaPods/Xcodeproj.git', ref: '70d114e'
end
```

**Comment by revolter** [comment]
To use this fix after it was officially released, simply run `bundle update xcodeproj`.

**Pull request merged**
