### PR TITLE
Update build settings for Xcode 9 Beta 6

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by dnkoutso** [comment]
Looks Xcode 9 to me.

**Comment by dnkoutso** [comment]
I think this should land if we can get a green build due to danger?

**Comment by segiddins** [comment]
@dnkoutso with or without the other PR that (I think) has more accurate settings (the ones from Xcode templates)

**Comment by dnkoutso** [comment]
sorry is that a question? are you suggesting that other pr supersedes this one?

**Comment by segiddins** [comment]
I'd like to merge them both, if others are comfortable with the changes in https://github.com/CocoaPods/Xcodeproj/pull/497

**Comment by CocoaPodsBarista** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: [31m
[!] Invalid `temporary_danger.rb` file: undefined local variable or method `pr_title` for #\<Danger::Dangerfile:0x000000032d86f8\>[0m
 #  from /tmp/d20170614-3529-1s44etf/temporary_danger.rb:25
 #  -------------------------------------------
 #      PP.pp @plist, ``
 \>    end
 #  
 #  -------------------------------------------

```
 #  from Dangerfile:2
 #  -------------------------------------------
 #  # Re-use CocoaPods' Dangerfile for CHANGELOG, xit and merge commit checks
 >  danger.import_dangerfile(github: "cocoapods/cocoapods")
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by CocoaPodsBarista** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: [31m
[!] Invalid `temporary_danger.rb` file: undefined local variable or method `pr_title` for #\<Danger::Dangerfile:0x000000021d09c8\>[0m
 #  from /tmp/d20170614-3541-1j7y39e/temporary_danger.rb:25
 #  -------------------------------------------
 #      PP.pp @plist, ``
 \>    end
 #  
 #  -------------------------------------------

```
 #  from Dangerfile:2
 #  -------------------------------------------
 #  # Re-use CocoaPods' Dangerfile for CHANGELOG, xit and merge commit checks
 >  danger.import_dangerfile(github: "cocoapods/cocoapods")
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Green!

**Comment by segiddins** [comment]
Going to install beta 2 and re-run, then 🚢

**Comment by segiddins** [comment]
xcode-install couldn't install beta 6, so someone else with beta six lying around should update

**Comment by segiddins** [comment]
Let's :ship: this @DanToml ?

**Comment by DanToml** [comment]
Yep!

**Comment by Coeur** [comment]
So now pods are building with gnu11 instead of gnu99?

**Comment by orta** [comment]
That's what it shows in the diff: https://github.com/CocoaPods/Xcodeproj/pull/496/files#diff-2fbe57544f33c804869fe7b12f1728eaR360

**Pull request merged**
