### PR TITLE
Added target type for TV application extensions

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by orta** [comment]
awww, really, another type :-/

**Comment by segiddins** [comment]
This will also need to be marked as an extension type in cocoapods.

**Comment by segiddins** [comment]
Needs a test, otherwise 👍🏻

**Comment by neonichu** [comment]
hm, so far we didn't do any tests for those constants — do we want to start doing that?

**Comment by segiddins** [comment]
No, if we don't have any it's fine. Just add a comma at the end of the line so rubocop passes, and :+1:

**Pull request merged**
