### PR TITLE
Add Xcode 11.4 object version.

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/CocoaPods/Xcodeproj/issues/744

### CODE REVIEW

**Comment by amorde** [comment]
What changed in the project format? Fine merging this but the version wouldn't bump without something changing right?

**Comment by dnkoutso** [comment]
Who knows? Apple bumps that number when they do...it seems from the issue report that Xcode 11.4 has a new version of 53.

**Comment by amorde** [comment]
I was under the impression it only gets bumped if something actually changes (ex. new attribute gets added)

this same topic came up last time https://github.com/CocoaPods/Xcodeproj/pull/687#discussion_r290145951

**Comment by dnkoutso** [comment]
Inteeeeresting....you are correct. I guess this doesnt matter since after we added this we are now more strict and crash for an unknown object version. This PR would fix the crash and we should get warnings for new attributes?

**Comment by amorde** [comment]
Don't we also crash on unknown attributes?

**Comment by dnkoutso** [comment]
No we warn for these.

**Comment by dnkoutso** [comment]
It actually says to file an issue in the warning.

**Comment by amorde** [comment]
As I see https://github.com/CocoaPods/Xcodeproj/blob/80a2cdabd49eaaeff177a132c97b393f7337fbc9/spec/project/object_spec.rb#L165

Would still prefer to actually add support for whatever changed but understand the need to fix crashes sooner rather than later

**Pull request merged**
