### PR TITLE
Add api to add SPM package to group

### PR DESCRIPTION
**Pull request by KarimAlweheshy**
https://github.com/CocoaPods/Xcodeproj/issues/846

### CODE REVIEW

**Comment by igor-makarov** [comment]
This is odd, I've managed to add local package refs with plain `new_reference` in my project:  
https://github.com/igor-makarov/xcoed/blob/564c4ae5dec1a3edb8154d33c146f776dec406bd/lib/xcoed.rb#L98

BTW you're totally welcome to check the project out, it's meant for [adding SwiftPM packages to Xcode](https://github.com/igor-makarov/xcoed) by utilizing a `Package.swift` file as a sort of 'Podfile'.

**Comment by KarimAlweheshy** [comment]
@igor-makarov Thanks Igor for the reference! Totally worked for me.
From my point of view, I think it would be nicer to have an out of the box solution to add a package without the domain knowledge of setting the `last_known_file_type` to `folder`. WDYT?

**Comment by igor-makarov** [comment]
Well, that's what I made the project for! It's meant to encapsulate the entire process of Xcode-SwiftPM integration.

**Comment by KarimAlweheshy** [comment]
I ended up using the api as you did. I found it hard to add a new dependency just to add this line. I hope this issue serves as a documentation for future wonderers

**Pull request closed without merging**
