### PR TITLE
Fixes path issues with CMake generated projects

### PR DESCRIPTION
**Pull request by mad-rain**
Hi!

Please see https://github.com/CocoaPods/CocoaPods/issues/6268 for more info.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fixes path issues with CMake generated projects  
  [mad-rain](https://github.com/mad-rain)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by segiddins** [comment]
Can you please add a changelog entry and a test for this change? Thanks!

**Comment by dnkoutso** [comment]
@mad-rain ping here.

**Comment by mad-rain** [comment]
@dnkoutso, unfortunately I have limited time to spend on this issue and I have zero Ruby experience. Any help is appreciated!

**Comment by amorde** [comment]
@mad-rain we can help out with tests, but I (personally) had a hard time following the issue that was mentioned. It sounded like CMake generates projects in a certain directory, and settings `PROJECT_DIR` to something that doesn't work with CocoaPods.

Do you have an easy example that we can try to reproduce the issue?

**Comment by jothepro** [comment]
@amorde I created a small example project for you to demonstrate the issue. Hope this helps :)
@mad-rain Pls check the code to ensure were talking about the same thing!

https://github.com/jothepro/cocoapods_cmake_issue

**Comment by paulb777** [comment]
Continued in #739

**Pull request closed without merging**
