### PR TITLE
Reworded warning without --project option

### LINKED ISSUE #709: Option `--project` suggested erroneously
It suggests that I use the `--project` option, and then says that option is unknown

```plain
% xcodeproj config-dump
[!] No Xcode project document found in the current working directory. Please specify which to use with the `--project` option.

✘ % xcodeproj config-dump --project Foobar.xcodeproj 
[!] Unknown option: `--project`
Did you mean: --verbose?
```

### PR DESCRIPTION
**Pull request by LemonSpike**
Fixes #709.

### CODE REVIEW

**Review by amorde — APPROVED** [review]
LGTM. Needs a rebase to handle conflicts in the changelog

**Comment by dnkoutso** [comment]
@LemonSpike please rebase this PR so we can merge it!

**Comment by LemonSpike** [comment]
Rebased! @amorde and @dnkoutso

**Review by segiddins — APPROVED** [review]

**Comment by dnkoutso** [comment]
@LemonSpike sorry for this can you please rebase one last time and make sure the CHANGELOG entry is in the correct spot?

**Pull request merged**
