### PR TITLE
Allow rebuilding fixtures of build settings from Xcode templates

### PR DESCRIPTION
**Pull request by segiddins**
This is a total WIP and I'm not sure we'll want to merge it, but I've spent maybe 15 hours working on it the past couple of days so I wanted to share what I was up to!

This PR allows us to rebuild the 'CommonBuildSettings' fixtures _without ever clicking a single button in Xcode_, by parsing the template files that Xcode itself uses to create the new targets.

### CODE REVIEW

**Comment by DanToml** [comment]
This is super cool!

**Comment by orta** [comment]
damn

**Comment by segiddins** [comment]
Pinging @mrackwitz just in case, since you wrote almost all of the code around gathering default build settings & testing them.

**Comment by segiddins** [comment]
Updated, this is mergeable if others are  👍

**Comment by dnkoutso** [comment]
👀  now

**Comment by dnkoutso** [comment]
I say go for it!

**Pull request merged**
