### PR TITLE
Xcode 8 devtoolscore workaround subprocess exec

### PR DESCRIPTION
**Pull request by segiddins**
An alternative to @neonichu's recent work ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by orta** [comment]
@segiddins / @neonichu do we have a preference between this and #404 ?

**Comment by DanToml** [comment]
@orta I think I'd rather this as it then doesn't effect users of Xcodeproj

**Comment by neonichu** [comment]
This 👍

**Comment by orta** [comment]
Cool, let's do it then

**Comment by mamaral** [comment]
Until a new version is updated, is there a way I can use the master branch now?

**Comment by segiddins** [comment]
@mamaral using a Gemfile (bundler.io) would probably be the easiest way

**Comment by orta** [comment]
https://guides.cocoapods.org/using/a-gemfile.html also

**Comment by mamaral** [comment]
@segiddins I hate to be that guy but can you give me more info? Does the location of the Gemfile matter? I created a Gemfile and added the following, but am not sure if thats remotely correct, then what I need to do after the fact, etc...

```
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'master'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'
```

**Comment by alloy** [comment]
@segiddins @neonichu Nice 👌

**Comment by orta** [comment]
@mamaral please read the guide I linked

**Comment by mamaral** [comment]
@orta Thanks, not sure how I missed that!

**Comment by gplocke** [comment]
One key step in that guide that I missed that has been stumping me for the last 3 hours or so was that you must now prefix all your "pod" commands with ""bundle exec".  Hopefully this comment will help someone else who overlooked the same thing.

So like:  `bundle exec pod repo push blah blah.podspec`

**Comment by shusso** [comment]
What release version did you guys plan this fix to go on?

**Comment by benasher44** [comment]
CocoaPods 1.1.0.rc.1

**Comment by arifken** [comment]
Just FYI, i field an issue for the CocoaPods project that seems like it might be related to this https://github.com/CocoaPods/CocoaPods/issues/5873. But maybe i'm not totally understanding how DevToolsCore works

**Pull request merged**
