### PR TITLE
Add support for numbers (real, integer) in PlistHelper

### PR DESCRIPTION
**Pull request by vincentisambart**

### CODE REVIEW

**Comment by neonichu** [comment]
Could you please elaborate on the rationale behind this change? AFAIK, Xcode itself only writes strings.

**Comment by vincentisambart** [comment]
When I wondered if it would be usefull, @alloy was telling me that "The plan was to extract [PlistHelper] once it was a full plist handler" https://twitter.com/alloy/status/560387301029994497.

The reason I needed that in the first place was to try reading the plist files generated by the Analyze action. I was already using Xcodeproj so, instead of using an other plist library I though I might as well use the one in Xcodeproj.

**Comment by neonichu** [comment]
Ah, I was missing that context :) Makes total sense, then. Could you add a changelog entry for this?

**Comment by vincentisambart** [comment]
Sure, I'll update the pull request tomorrow.

**Comment by vincentisambart** [comment]
Just updated CHANGELOG.md

**Comment by kylef** [comment]
Merged this one manually due to a merge conflict.

**Pull request closed without merging**
