### PR TITLE
Fixes issue CocoaPods/Xcodeproj#409

### PR DESCRIPTION
**Pull request by jeduden**
where can i best put tests for this particular issue ?

### CODE REVIEW

**Comment by segiddins** [comment]
Probably in the project spec, if you write out a small project file

**Comment by jeduden** [comment]
@segiddins  added a sample project and a test. the underlying issue was that this cases happens only when project that doesn't include the productRefGroup property.

**Comment by jeduden** [comment]
MMh: "An error occurred while installing activesupport (5.0.0.1), and Bundler cannot"  seems unrelated to PR.

**Comment by DanToml** [comment]
@jeduden Sorry about that, this should be fixed by #411

**Comment by DanToml** [comment]
@jeduden This should be good with a rebase

**Comment by jeduden** [comment]
done.

**Comment by jeduden** [comment]
@DanToml. the CI build is fixed. thanks!

**Comment by orta** [comment]
Cool, let's do this then 👍

**Pull request merged**
