### PR TITLE
Switch from unmaintained colored to maintained colored2

### PR DESCRIPTION
**Pull request by andrew**
The colored gem hasn't seen any activity in over 7 years, colored2 is a maintained fork, more details: https://libraries.io/rubygems/colored2

### CODE REVIEW

**Comment by orta** [comment]
It's possible that colored2 doesn't support ruby 2.0?

**Comment by orta** [comment]
Hrm, doesn't imply it - https://github.com/kigster/colored2/blob/master/colored2.gemspec#L20

**Comment by andrew** [comment]
Ah I didn't realise you needed support for both, will investigate, I'm sure we can add that back in

**Comment by andrew** [comment]
Oh you already did it, nice!

**Comment by orta** [comment]
:D

I had looked at doing this for danger before, but needed a push

**Comment by andrew** [comment]
Updated to require version `~> 3.1` 🍰

**Comment by DanToml** [comment]
This is great, thanks!

**Comment by orta** [comment]
Other places we need this: cork, cocoapods (danger)

**Pull request merged**
