### PR TITLE
Override Xcode 12 default for erroring on quoted imports in umbrellas

### PR DESCRIPTION
**Pull request by paulb777**
Fix https://github.com/CocoaPods/CocoaPods/issues/9902

### CODE REVIEW

**Comment by dnkoutso** [comment]
@paulb777 any reason not to do that in CocoaPods xcconfig settings instead?

**Comment by paulb777** [comment]
@dnkoutso No. I just didn't know it was possible there and I didn't find the right spot.

**Comment by dnkoutso** [comment]
I think you can do it in https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/build_settings.rb

**Comment by paulb777** [comment]
SG - I'll redo it there.

**Pull request closed without merging**
