### PR TITLE
[PlistHelper] Allow serializing ASCII Plists in Xcode 7 Beta 2

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/Xcodeproj/issues/278.

The parameter to `XCInitializeCoreIfNeeded` is whether or not the UI must also be initialized -- and we don't need UI :)

\c @neonichu @alloy

### CODE REVIEW

**Comment by alloy** [comment]
Probably a good idea to add a comment about what that parameter is.

**Comment by segiddins** [comment]
@alloy will do! Other than that, does this look OK?

**Comment by neonichu** [comment]
What about still checking the return value of `IDEInitialize()`? Or does this still return 0 for everything? If that is the case, we should remove the `IDEINITIALIZE_MAY_FAIL_VERSION` and `XCODE_VERSION` stuff, because it is unused.

**Comment by segiddins** [comment]
It still returns zero

**Comment by neonichu** [comment]
OK, then we should remove the unused constants with this PR.

**Comment by alloy** [comment]
@segiddins Yup :+1:

**Pull request merged**
