### PR TITLE
Add new Messages extension product types

### PR DESCRIPTION
**Pull request by neonichu**
Required for fixing CocoaPods/CocoaPods#5558

### CODE REVIEW

**Comment by segiddins** [comment]
@benasher44 these changes compatible with your work?
If so, 👍 & 🚢 @neonichu

**Comment by benasher44** [comment]
Yep! Lg2m. @neonichu do messages extensions get embedded the like watch 1 and app extensions? If so, I should update my CocoaPods PR to account for them once this is in.

**Comment by neonichu** [comment]
@benasher44 not sure, I have to check — but I assume they work similar to today extensions and the like.

**Comment by neonichu** [comment]
@benasher44 Looks like it works as expected: `Foo.app/PlugIns/MessagesExtension.appex`, so your PR should account for them 👌

**Comment by benasher44** [comment]
@neonichu okay thanks! I'm updating my PR, since it keeps a list of product types that need to be embedded. Does this apply to sticker packs as well (sorry should have asked about that too in the first place)?

**Comment by neonichu** [comment]
As far as I understand it, the sticker packs don't contain any code, so nothing to do there for CP.

**Pull request merged**
