### PR TITLE
Adds ui_test_bundle extension

### PR DESCRIPTION
**Pull request by 1nput0utput**
This is needed to put the right extension in xcake

### CODE REVIEW

**Comment by orta** [comment]
This looks good to me, anyone want to second that?

**Comment by dnkoutso** [comment]
LGTM.

**Comment by segiddins** [comment]
This needs a changelog entry...

**Comment by dnkoutso** [comment]
Ouch. @orta can we use the same mechanism in this repo like CocoaPods to prevent this from happening?

**Comment by dnkoutso** [comment]
https://github.com/CocoaPods/Xcodeproj/pull/481

**Comment by orta** [comment]
It would need Danger adding, probably isn't much effort at all.

**Pull request merged**
