### PR TITLE
Allowed to simply save a scheme after it was saved with a path before

### PR DESCRIPTION
**Pull request by Eldorado234**

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Eldorado234** [comment]
I know why I avoid rebasing 🙈

**Comment by orta** [comment]
Thanks @Eldorado234 - I forgot about that, figured I could just get away with it for ya'

**Comment by orta** [comment]
Looks good to me.

**Comment by Eldorado234** [comment]
Unfortunately, the changelog change didn't make it onto the master branch

**Pull request merged**
