### PR TITLE
Expand extension<->host relationship identification methods to all embeded targets

### PR DESCRIPTION
**Pull request by benasher44**
This will allow CocoaPods/CocoaPods#5502 to handle both extension and framework targets

### CODE REVIEW

**Comment by benasher44** [comment]
Still need to test this with the CocoaPods branch. Will update when that's done.

**Comment by benasher44** [comment]
Tested with CocoaPods branch, and we're good to go!

**Comment by segiddins** [comment]
👍🏻

**Comment by segiddins** [comment]
@benasher44 should I merge this now?

**Comment by benasher44** [comment]
@segiddins please! :)

**Pull request merged**
